Parse data from gsheets
dh-lab/db-interface pull request #36
Opened 2019-08-15 10:57 UTC by ilyamore88

2019-08-17 11:25 UTC, nikmel2803 requested changes
+ 
- удалить schema.json
- проверить что импортируются все данные (у меня импортируется 112 персон вместо 184)
- можно сделать разные функции для импортирования разных сущностей (`async importPersons(), async importLocations()`)

2019-08-17 11:25 UTC, nikmel2803 commented on bin/parserFromGSheets/index.js
> +    ranges: ['\'Персоны\'!A3:H132', '\'Персоны\'!A134:H150', '\'Персоны\'!A152:H185']
можно не хардкодить это?
например, получить все строки от 0 до той, на которой есть инфа (если такое API есть)
а строки-заголовки игнорить

2019-08-17 11:25 UTC, nikmel2803 commented on bin/parserFromGSheets/index.js
> +    personData.firstName.ru = row[0].trim();
можно `row = row.map(rowItem => rowItem.trim())` вместо постоянного вызова trim()

2019-08-17 11:25 UTC, nikmel2803 commented on bin/parserFromGSheets/index.js
> +    newPerson.save();
у меня скрипт завершает работу раньше, чем данные придут в БД
наверное, тут надо `await` (по крайней мере у меня заработало)

2019-08-17 21:40 UTC, ilyamore88 commented on bin/parserFromGSheets/index.js
> +    ranges: ['\'Персоны\'!A3:H132', '\'Персоны\'!A134:H150', '\'Персоны\'!A152:H185']
В любом случае интервал придётся задавать вручную. После таблицы с данными есть список ФИО, для которых данных ещё нет. Если считывать все данные с листа, то они тоже попадают в массив.

2019-08-18 20:40 UTC, nikmel2803 approved these changes

2019-08-18 22:12 UTC, merged