Search
dh-lab/db-interface pull request #4
Opened 2019-04-19 11:20 UTC by SemBystrov

2019-04-19 12:48 UTC, nikmel2803 requested changes

2019-04-19 12:48 UTC, nikmel2803 commented on frontend/src/router.js
> +      component: () => import(/* webpackChunkName: "home" */ './views/Form.vue')
```suggestion
      component: () => import(/* webpackChunkName: 'form' */ './views/Form.vue')
```

2019-04-19 12:48 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +    name: 'Catalog',
```suggestion
    name: 'Form',
```

2019-04-19 12:48 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +    data() {
удоли

2019-04-19 12:48 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +    methods: {
хватит оставлять за собой какашки

2019-04-21 12:52 UTC, nikmel2803 requested changes

2019-04-21 12:52 UTC, nikmel2803 commented on bin/readLocation.js
> +/**
Что это и для чего?
надо обновить документацию

2019-04-21 12:52 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +      locationLink: function (input) {
`locationLink(input) {`

2019-04-21 12:52 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +        <label for="person">Персона: </label>
привязка к полю по id не работает. Видимо, комонент это не поддерживает. Лучше удалить все id

2019-04-21 12:52 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +        <label for="quote">Цитата и ссылка на издание: </label>
Сделай плз, чтобы по умолчанию форма с цитатой вот так выглядела
![image](https://user-images.githubusercontent.com/32655339/56470317-6b7b1a80-644d-11e9-9884-aa46ca3943f8.png)

2019-04-22 09:35 UTC, nikmel2803 requested changes

2019-04-22 09:35 UTC, nikmel2803 commented on bin/readLocation.js
> + * reading json file with streets and insert them to DB
```suggestion
 * Read json file (data/streets.json) with streets and insert them to DB
```

2019-04-22 09:35 UTC, nikmel2803 commented on bin/readLocation.js
> +const locations = JSON.parse(str);
заменить этот код для чтения json на 
`const locations = require('./data/streets.json')`

2019-04-22 09:52 UTC, nikmel2803 approved these changes

2019-04-22 10:04 UTC, IraKaf approved these changes

2019-04-22 12:02 UTC, nikmel2803 requested changes

2019-04-22 12:02 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +      axios
1) используй всегда async/await
2) не надо слать запрос за json файлом. Надо его импортировать напрямую в компонент, тогда он будет сразу вшит в компонент формы.

2019-04-22 13:24 UTC, nikmel2803 approved these changes

2019-04-22 13:25 UTC, merged