relation in db
dh-lab/db-interface pull request #7
Opened 2019-04-23 13:43 UTC by SemBystrov

close #6

2019-04-24 03:47 UTC, nikmel2803 requested changes
Всё окей, маленькая правка в параметрах

2019-04-24 03:47 UTC, nikmel2803 commented on frontend/src/views/Form.vue
> +          rel: this.selRelation,
мне не очень нравятся эти сокращения. Мы нигде ничего не сокращали, так что давай и не будем. И код от этого становится чуть менее очевидным

2019-04-25 11:29 UTC, nikmel2803 approved these changes

2019-04-26 18:46 UTC, ilyamore88 approved these changes

2019-04-26 22:10 UTC, merged